(source melpa)

(depends-on "ack-and-a-half")
(depends-on "auto-complete")
(depends-on "color-theme")
(depends-on "dash-at-point")
(depends-on "grizzl")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "markdown-mode+")
(depends-on "pallet")
(depends-on "projectile")